### ISSUE TITLE
Can't build on windows.

### ISSUE THREAD

**Issue by leoniloris** [eclipse/paho.mqtt.rust#45]
I'm trying to `cargo build` on my machine but without success and the errors I get are not conveying any info. 

OpenSSL :
```
openssl.exe version
OpenSSL 1.1.1a  20 Nov 2018
```
_______________________________
* `cargo build` backtrace:
```
λ cargo build
    Updating crates.io index
  Downloaded env_logger v0.3.5
  Downloaded regex v0.1.80
  Downloaded regex-syntax v0.3.9
  Downloaded aho-corasick v0.5.3
  Downloaded utf8-ranges v0.1.3
  Downloaded thread_local v0.2.7
  Downloaded memchr v0.1.11
  Downloaded thread-id v2.0.0
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.58
   Compiling winapi v0.2.8
   Compiling cc v1.0.37
   Compiling cfg-if v0.1.9
   Compiling regex-syntax v0.3.9
   Compiling utf8-ranges v0.1.3
   Compiling log v0.4.6
   Compiling kernel32-sys v0.2.2
   Compiling log v0.3.9
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.3
   Compiling cmake v0.1.40
   Compiling paho-mqtt-sys v0.2.0 (C:\Users\test\paho.mqtt.rust\paho-mqtt-sys)
error: failed to run custom build command for `paho-mqtt-sys v0.2.0 (C:\Users\test\paho.mqtt.rust\paho-mqtt-sys)`
process didn't exit successfully: `C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-33fc5333b7858bbe\build-script-build` (exit code: 101)
--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_DEBUG


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\test\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:832:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:340
   9: cmake::fail
             at C:\Users\test\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:832
  10: cmake::run
             at C:\Users\test\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:810
  11: cmake::Config::build
             at C:\Users\test\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:719
  12: build_script_build::build::main
             at .\build.rs:149
  13: build_script_build::main
             at .\build.rs:57
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:49
  16: std::panicking::try::do_call<closure,i32>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:297
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libpanic_unwind\lib.rs:92
  18: std::panicking::try
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:276
  19: std::panic::catch_unwind
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panic.rs:388
  20: std::rt::lang_start_internal
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:48
  21: std::rt::lang_start<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  22: main
  23: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by fpagliughi** [comment]
I've never tried to build this on Windows. Actually I have never tried Rust on Windows either! But let's see if we can figure this out...

Try the build using the "very verbose" output flag (-vv). This will also show the build.rs output which might help us out:
```
cargo build -vv
```
Post the failing messages here.

**Comment by leoniloris** [comment]
Ok.
I tried with the RUST_BACKTRACE=1 as well.
The logs are here:
https://drive.google.com/file/d/1Aunp2KafphiqNis6mzsjRbP1Amvsc4GX/view?usp=sharing

**Comment by fpagliughi** [comment]
OK, just to put a little bit here of the relevant parts:
```
[paho-mqtt-sys 0.2.0] running: "cmake" "C:\\Users\\test\\paho.mqtt.rust\\paho-mqtt-sys\\paho.mqtt.c/" "-G" "Visual Studio 15 2017" "-Thost=x64" "-Ax64" "-DPAHO_BUILD_STATIC=on" "-DPAHO_WITH_SSL=on" "-DOPENSSL_SEARCH_PATH=C:\\Program Files\\OpenSSL-Win64" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\test\\\\paho.mqtt.rust\\target\\debug\\build\\paho-mqtt-sys-e401b061728e879d\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_BUILD_TYPE=Debug"
[paho-mqtt-sys 0.2.0] -- CMake version: 3.15.0-rc1
[paho-mqtt-sys 0.2.0] -- CMake system name: Windows
[paho-mqtt-sys 0.2.0] -- Timestamp is 2019-06-17T14:44:32Z
[paho-mqtt-sys 0.2.0] -- OpenSSL hints: C:/OpenSSL-Win64
[paho-mqtt-sys 0.2.0] -- OpenSSL headers found at C:/OpenSSL-Win64/include
[paho-mqtt-sys 0.2.0] -- OpenSSL library found at C:/OpenSSL-Win64/lib/libssl.lib
[paho-mqtt-sys 0.2.0] -- OpenSSL Crypto library found at C:/OpenSSL-Win64/lib/libcrypto.lib
[paho-mqtt-sys 0.2.0] -- OpenSSL hints: C:/OpenSSL-Win64
[paho-mqtt-sys 0.2.0] -- OpenSSL headers found at C:/OpenSSL-Win64/include
[paho-mqtt-sys 0.2.0] -- Configuring done
[paho-mqtt-sys 0.2.0] -- Generating done
[paho-mqtt-sys 0.2.0] -- Build files have been written to: C:/Users/test/paho.mqtt.rust/target/debug/build/paho-mqtt-sys-e401b061728e879d/out/build
[paho-mqtt-sys 0.2.0] running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[paho-mqtt-sys 0.2.0] Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
[paho-mqtt-sys 0.2.0] Copyright (C) Microsoft Corporation. All rights reserved.
[paho-mqtt-sys 0.2.0]
[paho-mqtt-sys 0.2.0]   MQTTProtocolClient.c
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\Socket.h(47): fatal error C1083: Impossible d'ouvrir le fichier include�: 'sys/socket.h'�: No such file or directory [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0]   Clients.c
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2143: erreur de syntaxe�: absence de ')' avant '(' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2091: fonction retourn�e par la fonction [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2143: erreur de syntaxe�: absence de ')' avant 'cha�ne' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2143: erreur de syntaxe�: absence de '{' avant 'cha�ne' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2059: erreur de syntaxe�: 'cha�ne' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(67): error C2059: erreur de syntaxe�: ')' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(85): error C2143: erreur de syntaxe�: absence de ')' avant '(' [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
[paho-mqtt-sys 0.2.0] c:\users\test\paho.mqtt.rust\paho-mqtt-sys\paho.mqtt.c\src\MQTTProperties.h(85): error C2091: fonction retourn�e par la fonction [C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\build\src\common_obj.vcxproj]
```

And then a few hundred more error that are similar...

**Comment by fpagliughi** [comment]
On the plus side: There's a good version of CMake (3.15), and it appears to be finding the OpenSSL library in C:\OpenSSL-Win64, correct?

Do you know what version of Visual Studio you have installed (though I don't think that's the problem).

The first error is a good hint at the problem. It's hitting an error in the Paho C library at Socket.h, Line 47. That's in a conditional compilation block for non-Windows builds. So, for some reason, the C library build is not recognizing Windows? 

That's from:
```
#if defined(WIN32) || defined(WIN64)
```
Is there some new issue with the Microsoft compilers? Do they use _WIN32, _WIN64 now? Or something like that?

**Comment by leoniloris** [comment]
sorry for the delay.
So, I changed every instance of WIN32/64 I found to _WIN32/64 and the build advanced. But it fails in the linking of the paho without much detail:

```
cargo:root=C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out
debug:link Using SSL library
Error building Paho C library: 'C:\Users\test\paho.mqtt.rust\target\debug\build\paho-mqtt-sys-e401b061728e879d\out\lib\libpaho-mqtt3as-static.a'
```

**Comment by leoniloris** [comment]
Got it to build by changing:
```
@@ -169,9 +197,15 @@ mod build {
             lib_path = "lib64";
         }

-        let link_lib = link_lib();
-        let link_file = format!("lib{}.a", link_lib);
+        let link_lib = link_lib();
+        let link_file = format!("{}.lib", link_lib);
``` 
in paho-mqtt-sys/paho.mqtt.c

**Comment by leoniloris** [comment]
These worked for me.

https://github.com/leoniloris/paho.mqtt.rust
https://github.com/leoniloris/paho.mqtt.c

**Comment by leoniloris** [comment]
Should I open a PR in both repos?

**Comment by fpagliughi** [comment]
Yes, we would need a separate PR for each repository. I don't have control of the Paho C library, so we would need to make sure the request makes sense for them, too; why it's necessary, and that it doesn't break anything. What compiler are you using to build the C lib?

On the Rust side, what you propose makes sense. I found an old laptop in the closet with a working version of Win7 on it and Visual Studio 2015. I can start testing later this week.

**Comment by leoniloris** [comment]
Alright.

My compiler version:
    - `Microsoft (R) C/C++ version 19.16.27027.1`
cmake version:
     - `3.15.0-rc1`

**Comment by fpagliughi** [comment]
I fixed the build.rs with a number of updates including the conditional to figure out the name of the library if it's on Window. I also turned off the build of the Paho C tests. That seemed to fix the C build even without the WIN32 updates to that library. 

This is in the 'develop' branch.

But I'm still having two issues:

 1. I can't seem to build with OpenSSL. I tried v1.0.2 and v1.1.1. I just get a pile of linker errors.

 2. I can build the non-SSL version, but the examples apps don't seem to run. I get something like this for most of the apps:

```
>async_publish.exe
Unable to connect: :
```

**Comment by uhuntu** [comment]
```
diff --git a/paho-mqtt-sys/build.rs b/paho-mqtt-sys/build.rs
index 252c14a..14e428b 100644
--- a/paho-mqtt-sys/build.rs
+++ b/paho-mqtt-sys/build.rs
@@ -156,7 +156,8 @@ mod build {
         cmk_cfg
             .define("PAHO_BUILD_STATIC", "on")
             .define("PAHO_ENABLE_TESTING", "off")
-            .define("PAHO_WITH_SSL", ssl);
+            .define("PAHO_WITH_SSL", ssl)
+            .cflag("/DWIN32");

         if let Ok(ssl_sp) = env::var("OPENSSL_SEARCH_PATH") {
             cmk_cfg.define("OPENSSL_SEARCH_PATH", format!("{}", ssl_sp));
```

**Comment by uhuntu** [comment]
#54

**Comment by uhuntu** [comment]
```
diff --git a/src/MQTTAsync.c b/src/MQTTAsync.c
index b750f9f..24ce16b 100644
--- a/src/MQTTAsync.c
+++ b/src/MQTTAsync.c
@@ -2809,6 +2809,22 @@ int MQTTAsync_connect(MQTTAsync handle, const MQTTAsync_connectOptions* options)
        int rc = MQTTASYNC_SUCCESS;
        MQTTAsync_queuedCommand* conn;

+       if (mqttasync_mutex == NULL)
+       {
+               mqttasync_mutex = CreateMutex(NULL, 0, NULL);
+               mqttcommand_mutex = CreateMutex(NULL, 0, NULL);
+               send_sem = CreateEvent(
+               NULL,               /* default security attributes */
+               FALSE,              /* manual-reset event? */
+               FALSE,              /* initial state is nonsignaled */
+               NULL                /* object name */
+               );
+               stack_mutex = CreateMutex(NULL, 0, NULL);
+               heap_mutex = CreateMutex(NULL, 0, NULL);
+               log_mutex = CreateMutex(NULL, 0, NULL);
+               socket_mutex = CreateMutex(NULL, 0, NULL);
+       }
+
        FUNC_ENTRY;
        if (options == NULL)
        {
```

**Comment by fpagliughi** [comment]
There were a number of issues related to this that we found in the upstream Paho C library. Those have all been fixed in the latest 1.3.2 release, which this Rust crate will wrap starting at v0.7.

I also added a few updates to the `build.rs` file to do a better job of finding the SSL libraries.

And I have a Windows machine now! So I can actually test on Windows and make sure this works.

**Comment by sweetim** [comment]
error compiling on Windows, any idea how to fix this?

```
running: "cmake" "C:\\Users\\hoswe\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\paho-mqtt-sys-0.3.0\\paho.mqtt.c/" "-G" "Visual Studio 16 2019" "-Thost=x86" "-AWin32" "-DPAHO_BUILD_SHARED=off" "-DPAHO_BUILD_STATIC=on" "-DPAHO_ENABLE_TESTING=off" "-DPAHO_WITH_SSL=on" "-DCMAKE_INSTALL_PREFIX=D:\\workspace\\dyson-rs\\target\\debug\\build\\paho-mqtt-sys-b97c99ae8f392d84\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro /DWIN32" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro /DWIN32" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- CMake version: 3.17.2
-- CMake system name: Windows
-- Timestamp is 2020-05-18T14:03:13Z
-- Configuring done
-- Generating done
-- Build files have been written to: D:/workspace/dyson-rs/target/debug/build/paho-mqtt-sys-b97c99ae8f392d84/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  common_obj_static.vcxproj -> D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\common_obj_static.dir\Debug\common_obj_static.lib
  common_ssl_obj_static.vcxproj -> D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\common_ssl_obj_static.dir\Debug\common_ssl_obj_static.lib
  MQTTAsync.c
  paho-mqtt3a-static.vcxproj -> D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\Debug\paho-mqtt3a-static.lib
  MQTTClient.c
C:\Users\hoswe\.cargo\registry\src\github.com-1ecc6299db9ec823\paho-mqtt-sys-0.3.0\paho.mqtt.c\src\MQTTClient.c(376,66): error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(PINIT_ONCE,PVOID,PVOID *)' to 'PINIT_ONCE_FN' [D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\paho-mqtt3c-static.vcxproj]
C:\Users\hoswe\.cargo\registry\src\github.com-1ecc6299db9ec823\paho-mqtt-sys-0.3.0\paho.mqtt.c\src\MQTTClient.c(376,66): warning C4024: 'InitOnceExecuteOnce': different types for formal and actual parameter 2 [D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\paho-mqtt3c-static.vcxproj]
  MQTTAsync.c
  SSLSocket.c
  Generating Code...
  paho-mqtt3as-static.vcxproj -> D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\Debug\paho-mqtt3as-static.lib
  MQTTClient.c
C:\Users\hoswe\.cargo\registry\src\github.com-1ecc6299db9ec823\paho-mqtt-sys-0.3.0\paho.mqtt.c\src\MQTTClient.c(376,66): error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(PINIT_ONCE,PVOID,PVOID *)' to 'PINIT_ONCE_FN' [D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\paho-mqtt3cs-static.vcxproj]
C:\Users\hoswe\.cargo\registry\src\github.com-1ecc6299db9ec823\paho-mqtt-sys-0.3.0\paho.mqtt.c\src\MQTTClient.c(376,66): warning C4024: 'InitOnceExecuteOnce': different types for formal and actual parameter 2 [D:\workspace\dyson-rs\target\debug\build\paho-mqtt-sys-b97c99ae8f392d84\out\build\src\paho-mqtt3cs-static.vcxproj]

--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1
```

**Comment by fpagliughi** [comment]
Is this the latest version of the Rust crate? 0.7.1?

**Comment by sweetim** [comment]
yes it is, in `Cargo.toml` file
```
paho-mqtt = "0.7.1"
```

**Comment by gabrik** [comment]
Same error:

```
error: failed to run custom build command for `paho-mqtt-sys v0.3.0`

Caused by:
  process didn't exit successfully: `<omissis>\target\debug\build\paho-mqtt-sys-caa0a71eef1729f4\build-script-build` (exit code: 101)
  --- stdout
  debug:Running the bundled build for Paho C
  cargo:rerun-if-changed=build.rs
  running: "cmake" "<omissis>\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\paho-mqtt-sys-0.3.0\\paho.mqtt.c/" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DPAHO_BUILD_SHARED=off" "-DPAHO_BUILD_STATIC=on" "-DPAHO_ENABLE_TESTING=off" "-DPAHO_WITH_SSL=on" "-DCMAKE_INSTALL_PREFIX=<omissis>\\target\\debug\\build\\paho-mqtt-sys-29210c5ca182f295\\out" "-DCMAKE_C_FLAGS= /DWIN32 -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= /DWIN32 -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
  -- The C compiler identification is MSVC 19.27.29111.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- CMake version: 3.18.3
  -- CMake system name: Windows
  -- The CXX compiler identification is MSVC 19.27.29111.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Timestamp is 2020-09-24T17:37:38Z
  -- Configuring incomplete, errors occurred!
  See also "<omissis>/target/debug/build/paho-mqtt-sys-29210c5ca182f295/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:157 (if):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:34 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:177 (elseif):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:34 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
    system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
    OPENSSL_INCLUDE_DIR)
  Call Stack (most recent call first):
    C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    C:/Program Files/CMake/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
    src/CMakeLists.txt:186 (find_package)


  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', <omissis>\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm supposed to install OpenSSL or some other dependecy?

OS: Windows 10 2004
Crate: paho-mqtt 0.7.1
